# Site settings
title: The SystemIdle Blog
email: blogmaster@systemidle.com
description: > # this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.systemidle.com" # the base hostname & protocol for your site
twitter_username: AlanMullett
github_username:  AlanMullett

# Build settings
markdown: kramdown
